Validate multiple commits #ISS-0017 [enhancement]

diff --git a/.github/workflows/check-commit-message.yml b/.github/workflows/check-commit-message.yml
--- a/.github/workflows/check-commit-message.yml
+++ b/.github/workflows/check-commit-message.yml
@@ -17,5 +17,9 @@ jobs:
       
       - name: Validate commit message format
         run: |
-          COMMIT_MSG=$(git log --format=%B --no-merges -n 1 ${{ github.sha }})
-          echo "$COMMIT_MSG" | grep -E '^.+#[A-Z]{3}-[0-9]{4}\s*\[(task|bugfix|feature|enhancement)\]$' || (echo "Erro: Commit message has no valid format!" && exit 1)
+          INVALID_COMMITS=$(git log --format=%B --no-merges ${{ github.event.before }}..${{ github.sha }} | grep -vE '^.+#[A-Z]{3}-[0-9]{4}\s*\[(bugfix|task|feature)\]$' || true)
+          if [ -n "$INVALID_COMMITS" ]; then
+            echo "Erro: The following commits do not follow the expected pattern:"
+            echo "$INVALID_COMMITS"
+            exit 1
+          fi
